# Generated by Django 4.1.1 on 2022-10-09 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='記事の見出しを入力してください', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='詳細ページurlに用いる文字列を入力してください', max_length=20, null=True)),
                ('description', models.TextField(help_text='記事の説明を入力してください', max_length=1000)),
                ('content', models.TextField(help_text='記事の内容をHTML形式で入力してください', max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='投稿のジャンルを入力してください', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='詳細ページurlに用いる文字列を入力してください', max_length=20, null=True)),
                ('subject', models.CharField(blank=True, choices=[('I', '数学I'), ('II', '数学II'), ('III', '数学III'), ('A', '数学A'), ('B', '数学B'), ('C', '数学C')], help_text='このプレイリストの科目してください', max_length=200, null=True)),
                ('chapter', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['subject', 'chapter'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='モジュール名を入力してください', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='詳細ページurlに用いる文字列を入力してください', max_length=20, null=True)),
                ('description', models.TextField(help_text='この用語の説明を入力してください', max_length=1000)),
                ('genres', models.ManyToManyField(help_text='この記事のジャンルを選んでください', to='ugosite.genre')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='問題名を入力してください', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='問題ページurlに用いる文字列を入力してください', max_length=20, null=True)),
                ('text', models.TextField(help_text='この問題の内容をTeX形式で入力してください', max_length=1000)),
                ('source', models.CharField(blank=True, help_text='この問題のの引用元を入力してください', max_length=200, null=True)),
                ('answer', models.TextField(blank=True, help_text='この問題の解答例をTeX形式で入力してください', max_length=1000, null=True, verbose_name='example_answer')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugosite.article')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugosite.module')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用語名を入力してください', max_length=200)),
                ('hurigana', models.CharField(default='ふりがな', help_text='ふりがなを入力してください', max_length=200)),
                ('en_name', models.CharField(blank=True, help_text='英語名を入力してください', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='詳細ページurlに用いる文字列を入力してください', max_length=20, null=True)),
                ('description', models.TextField(help_text='この用語の説明を入力してください', max_length=1000)),
                ('genres', models.ManyToManyField(help_text='この記事のジャンルを選んでください', to='ugosite.genre')),
            ],
            options={
                'ordering': ['hurigana'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='この動画のタイトルを入力してください', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='解説動画のYoutubeIDを入力してください', max_length=20, null=True)),
                ('table', models.TextField(blank=True, help_text='この動画の目次を入力してください', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, help_text='この動画の説明を入力してください', max_length=1000, null=True)),
                ('data', models.JSONField(help_text='このFieldはYoutubeAPIによって読み込まれます。', null=True)),
                ('problem', models.OneToOneField(blank=True, help_text='問題を指定してください', null=True, on_delete=django.db.models.deletion.CASCADE, to='ugosite.problem')),
                ('terms', models.ManyToManyField(help_text='この記事に関連する用語を選んでください', to='ugosite.term')),
            ],
            options={
                'ordering': ['data__snippet__publishedAt'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='このプレイリストの名前入力してください', max_length=200, null=True)),
                ('title', models.CharField(blank=True, help_text='このプレイリストのタイトル入力してください', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='このプレイリストのYoutubeIDを入力してください', max_length=20, null=True)),
                ('description', models.TextField(help_text='このプレイリストの説明を入力してください', max_length=1000, null=True)),
                ('type', models.CharField(blank=True, choices=[('C', '単元別'), ('T', 'テーマ別'), ('O', 'その他')], help_text='このプレイリストの科目してください', max_length=200, null=True)),
                ('data', models.JSONField(help_text='このFieldはYoutubeAPIによって読み込まれます。', null=True)),
                ('genres', models.ManyToManyField(help_text='このプレイリストのジャンルを選んでください', to='ugosite.genre')),
                ('videos', models.ManyToManyField(blank=True, help_text='このプレイリストが含む動画を選んでください', to='ugosite.video')),
            ],
            options={
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='このノートのタイトルを入力してください', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='解説動画のYoutubeIDを入力してください', max_length=20, null=True)),
                ('description', models.TextField(help_text='このノートの説明を入力してください', max_length=1000)),
                ('svg', models.TextField(help_text='このノートの内容をSVG形式で書いてください', max_length=10000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='このコメントの内容を入力してください', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugosite.article')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='modules',
            field=models.ManyToManyField(help_text='この記事を含むモジュールを選んでください', to='ugosite.module'),
        ),
        migrations.AddField(
            model_name='article',
            name='terms',
            field=models.ManyToManyField(help_text='この記事に関連する用語を選んでください', to='ugosite.term'),
        ),
    ]
