# Generated by Django 4.1.1 on 2022-10-09 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
