# Generated by Django 4.1.1 on 2022-10-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0002_video_pub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, help_text='このプレイリストのYoutubeIDを入力してください', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.TextField(blank=True, help_text='この用語の説明を入力してください', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='この記事のジャンルを選んでください', to='ugosite.genre'),
        ),
    ]
