# Generated by Django 4.1.1 on 2022-10-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0003_alter_video_options_alter_playlist_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['pub']},
        ),
    ]
