# Generated by Django 4.1.1 on 2022-10-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0005_video_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='親ジャンルを指定してください', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugosite.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, help_text='詳細ページurlに用いる文字列を入力してください', null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='subject',
            field=models.CharField(blank=True, choices=[('I', '数学I'), ('II', '数学II'), ('III', '数学III'), ('A', '数学A'), ('B', '数学B'), ('C', '数学C')], help_text='このジャンルの科目してください', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(help_text='この用語の説明を入力してください', max_length=5000),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(help_text='このプレイリストの説明を入力してください', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='このプレイリストのジャンルを選んでください', to='ugosite.genre'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.TextField(blank=True, help_text='この問題の内容をTeX形式で入力してください', max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='この動画の説明を入力してください', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='terms',
            field=models.ManyToManyField(blank=True, help_text='この記事に関連する用語を選んでください', to='ugosite.term'),
        ),
    ]
