# Generated by Django 4.1.1 on 2022-10-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0007_genre_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(blank=True, choices=[('SUB', '科目'), ('CHA', '章'), ('SEC', '節'), ('SSE', '分節')], help_text='このジャンルの科目してください', max_length=200, null=True),
        ),
    ]
