# Generated by Django 4.1.1 on 2022-10-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0010_alter_genre_options_video_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='title',
            field=models.CharField(blank=True, help_text='このプレイリストのタイトル入力してください', max_length=200, null=True),
        ),
    ]
