# Generated by Django 4.1.1 on 2022-10-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0012_alter_video_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='ジャンルを選んでください', to='ugosite.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(blank=True, choices=[('SUB', '科目'), ('CHA', '章'), ('SEC', '節'), ('SSE', '分節'), ('STU', '研究'), ('DEV', '発展'), ('SUP', '補足'), ('PRA', '演習')], help_text='このジャンルの科目してください', max_length=200, null=True),
        ),
    ]
