# Generated by Django 4.1.1 on 2022-10-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0013_problem_genres_alter_genre_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='problem',
        ),
        migrations.AddField(
            model_name='video',
            name='problems',
            field=models.ManyToManyField(blank=True, help_text='問題を指定してください', to='ugosite.problem'),
        ),
    ]
