# Generated by Django 4.1.1 on 2022-10-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0014_remove_video_problem_video_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='module',
        ),
        migrations.AddField(
            model_name='problem',
            name='modules',
            field=models.ManyToManyField(blank=True, to='ugosite.module'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, help_text='問題ページurlに用いる文字列を入力してください', null=True),
        ),
    ]
