# Generated by Django 4.1.1 on 2022-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0015_remove_problem_module_problem_modules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='problems',
            field=models.ManyToManyField(blank=True, help_text='この記事に含まれる問題を選んでください', to='ugosite.problem'),
        ),
        migrations.AlterField(
            model_name='module',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='この記事のジャンルを選んでください', to='ugosite.genre'),
        ),
    ]
