# Generated by Django 4.1.1 on 2022-10-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0016_remove_problem_modules_module_problems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, help_text='詳細ページurlに用いる文字列を入力してください', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, help_text='この用語の説明を入力してください', max_length=10000),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, help_text='詳細ページurlに用いる文字列を入力してください', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(help_text='このプレイリストの説明を入力してください', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, help_text='このプレイリストのYoutubeIDを入力してください', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.TextField(blank=True, help_text='この問題の解答例をTeX形式で入力してください', max_length=10000, null=True, verbose_name='example_answer'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, help_text='問題ページurlに用いる文字列を入力してください', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='この動画の説明を入力してください', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, help_text='解説動画のYoutubeIDを入力してください', max_length=100, null=True),
        ),
    ]
