# Generated by Django 4.1.1 on 2022-10-16 07:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0017_alter_genre_slug_alter_module_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='newTable',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, max_length=1000, null=True, size=None),
        ),
    ]
