# Generated by Django 4.1.1 on 2022-10-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0018_video_newtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='table',
        ),
    ]
