# Generated by Django 4.1.1 on 2022-10-16 08:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0019_remove_video_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='newTable',
        ),
        migrations.AddField(
            model_name='video',
            name='table',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, help_text='この動画の目次を入力してください', max_length=1000, null=True, size=None),
        ),
    ]
