# Generated by Django 4.1.1 on 2022-10-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0020_remove_video_newtable_video_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='table',
            new_name='newTable',
        ),
    ]
