# Generated by Django 4.1.1 on 2022-10-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0021_rename_table_video_newtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='newTable',
            new_name='table',
        ),
    ]
