# Generated by Django 4.1.1 on 2022-10-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0022_rename_newtable_video_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='article',
        ),
    ]
