# Generated by Django 4.1.1 on 2022-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0023_remove_problem_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='problems',
            field=models.ManyToManyField(blank=True, help_text='この記事に含まれる問題を選んでください', to='ugosite.problem'),
        ),
    ]
