# Generated by Django 4.1.1 on 2022-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0025_remove_module_problems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='記事の内容をHTML形式で入力してください', max_length=2000),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='記事の説明を入力してください', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='この記事を含むモジュールを選んでください', to='ugosite.module'),
        ),
        migrations.AlterField(
            model_name='article',
            name='terms',
            field=models.ManyToManyField(blank=True, help_text='この記事に関連する用語を選んでください', to='ugosite.term'),
        ),
    ]
