# Generated by Django 4.1.1 on 2022-10-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0026_alter_article_options_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='このノートのタイトルを入力してください', max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='note',
            name='svg',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, help_text='このノートの内容を入力してください', max_length=10000),
        ),
        migrations.AddField(
            model_name='note',
            name='folders',
            field=models.ManyToManyField(blank=True, help_text='このノートのフォルダを指定してください', to='ugosite.folder'),
        ),
    ]
