# Generated by Django 4.1.1 on 2022-10-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0027_folder_alter_note_options_remove_note_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='path',
            field=models.CharField(blank=True, help_text='このノートのタイトルを入力してください', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, help_text='このノートの名前', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(blank=True, help_text='このフォルダの名前', max_length=200, null=True),
        ),
    ]
