# Generated by Django 4.1.1 on 2022-10-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0029_note_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folders',
            field=models.ManyToManyField(blank=True, help_text='このフォルダが含まれるフォルダを指定してください', to='ugosite.folder'),
        ),
    ]
