# Generated by Django 4.1.1 on 2022-10-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0030_folder_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.CharField(blank=True, help_text='このフォルダのpathを入力してください', max_length=200, null=True),
        ),
    ]
