# Generated by Django 4.1.1 on 2022-10-23 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0031_alter_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='このノートの作成日を指定してください'),
        ),
        migrations.AddField(
            model_name='note',
            name='update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='このノートの更新日を指定してください'),
        ),
    ]
