# Generated by Django 4.1.1 on 2022-10-23 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0032_note_created_date_note_update_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='folder',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='このフォルダの作成日を指定してください'),
        ),
        migrations.AddField(
            model_name='folder',
            name='update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='このフォルダの更新日を指定してください'),
        ),
    ]
