# Generated by Django 4.1.1 on 2022-10-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0033_alter_note_options_folder_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_date']},
        ),
    ]
