# Generated by Django 4.1.1 on 2022-10-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0034_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(blank=True, choices=[('C', '単元別'), ('T', 'テーマ別'), ('O', 'その他')], help_text='このプレイリストの科目してください', max_length=200, null=True),
        ),
    ]
