# Generated by Django 4.1.1 on 2022-10-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0035_module_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
    ]
