# Generated by Django 4.1.1 on 2022-10-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0036_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='parent',
            new_name='parent_genre',
        ),
        migrations.AddField(
            model_name='term',
            name='related_terms',
            field=models.ManyToManyField(blank=True, help_text='この用語に関連する用語を選んでください', to='ugosite.term'),
        ),
        migrations.AlterField(
            model_name='term',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='この用語のジャンルを選んでください', to='ugosite.genre'),
        ),
    ]
