# Generated by Django 4.1.1 on 2022-10-24 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0037_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='parent_module',
            field=models.ForeignKey(blank=True, help_text='親モジュールを選んでください', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugosite.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='このモジュールのジャンルを選んでください', to='ugosite.genre'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(blank=True, choices=[('C', '単元別'), ('T', 'テーマ別'), ('O', 'その他')], help_text='このモジュールの種類を選択してください', max_length=200, null=True),
        ),
    ]
