# Generated by Django 4.1.1 on 2022-10-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0039_alter_article_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, help_text='記事のタイトルを入力してください', max_length=200, null=True),
        ),
    ]
