# Generated by Django 4.1.1 on 2022-10-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0040_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='headline',
        ),
    ]
