# Generated by Django 4.1.1 on 2022-10-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0041_remove_article_headline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='created_date',
        ),
    ]
