# Generated by Django 4.1.2 on 2022-10-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0042_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='name',
        ),
    ]
