# Generated by Django 4.1.2 on 2022-10-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0043_rename_title_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.CharField(blank=True, help_text='このジャンルのアイコンSVG', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(blank=True, help_text='このジャンルのタイトル入力してください', max_length=200, null=True),
        ),
    ]
